const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        AlignmentType, HeadingLevel, WidthType, BorderStyle, ShadingType,
        LevelFormat, PageBreak } = require("docx");
const fs = require("fs");

// ─── Helpers ────────────────────────────────────────────────────────────────
const b  = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const bH = { style: BorderStyle.SINGLE, size: 1, color: "1F4E79" };
const borders  = { top: b,  bottom: b,  left: b,  right: b  };
const bordersH = { top: bH, bottom: bH, left: bH, right: bH };
const cellMargins = { top: 80, bottom: 80, left: 140, right: 140 };

const h1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, pageBreakBefore: false,
    spacing: { before: 360, after: 180 },
    children: [new TextRun({ text: t, font: "Arial", size: 36, bold: true, color: "1F4E79" })] });

const h2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 120 },
    children: [new TextRun({ text: t, font: "Arial", size: 28, bold: true, color: "2E75B6" })] });

const h3 = t => new Paragraph({ heading: HeadingLevel.HEADING_3,
    spacing: { before: 200, after: 80 },
    children: [new TextRun({ text: t, font: "Arial", size: 24, bold: true, color: "404040" })] });

const p = t => new Paragraph({ spacing: { before: 80, after: 80 },
    children: [new TextRun({ text: t, font: "Arial", size: 22 })] });

const pb = (bold, rest="") => new Paragraph({ spacing: { before: 80, after: 80 },
    children: [ new TextRun({ text: bold, font: "Arial", size: 22, bold: true }),
                new TextRun({ text: rest,  font: "Arial", size: 22 }) ] });

const code = t => new Paragraph({ spacing: { before: 40, after: 40 }, indent: { left: 560 },
    children: [new TextRun({ text: t, font: "Courier New", size: 19, color: "1F3864" })] });

const bullet = (t, lvl=0) => new Paragraph({ spacing: { before: 40, after: 40 },
    numbering: { reference: "bullets", level: lvl },
    children: [new TextRun({ text: t, font: "Arial", size: 22 })] });

const numbered = (t, lvl=0) => new Paragraph({ spacing: { before: 60, after: 60 },
    numbering: { reference: "numbers", level: lvl },
    children: [new TextRun({ text: t, font: "Arial", size: 22 })] });

const note = t => new Paragraph({ spacing: { before: 120, after: 120 }, indent: { left: 400 },
    children: [ new TextRun({ text: "NOTE: ", font: "Arial", size: 22, bold: true, color: "2E75B6" }),
                new TextRun({ text: t, font: "Arial", size: 22, italics: true }) ] });

const gap = () => new Paragraph({ spacing: { before: 80, after: 80 }, children: [new TextRun("")] });

const PB = () => new Paragraph({ children: [new PageBreak()] });

function tbl(headers, rows, widths) {
    return new Table({
        width: { size: widths.reduce((a,b)=>a+b,0), type: WidthType.DXA },
        columnWidths: widths,
        rows: [
            new TableRow({ tableHeader: true, children: headers.map((h,i) =>
                new TableCell({ borders: bordersH, width: { size: widths[i], type: WidthType.DXA },
                    shading: { fill: "1F4E79", type: ShadingType.CLEAR }, margins: cellMargins,
                    children: [new Paragraph({ children: [new TextRun({ text: h, font: "Arial", size: 20, bold: true, color: "FFFFFF" })] })] })
            )}),
            ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) =>
                new TableCell({ borders, width: { size: widths[ci], type: WidthType.DXA },
                    shading: { fill: ri%2===0 ? "EBF3FB" : "FFFFFF", type: ShadingType.CLEAR }, margins: cellMargins,
                    children: [new Paragraph({ children: [new TextRun({ text: cell, font: "Arial", size: 20 })] })] })
            )}))
        ]
    });
}

// ─── Document ────────────────────────────────────────────────────────────────
const doc = new Document({
    numbering: { config: [
        { reference: "bullets", levels: [
            { level:0, format:LevelFormat.BULLET, text:"•", alignment:AlignmentType.LEFT,
              style:{ paragraph:{ indent:{ left:500, hanging:260 } } } },
            { level:1, format:LevelFormat.BULLET, text:"-", alignment:AlignmentType.LEFT,
              style:{ paragraph:{ indent:{ left:900, hanging:260 } } } }
        ]},
        { reference: "numbers", levels: [
            { level:0, format:LevelFormat.DECIMAL, text:"%1.", alignment:AlignmentType.LEFT,
              style:{ paragraph:{ indent:{ left:500, hanging:260 } } } }
        ]}
    ]},
    sections: [{ properties: { page: {
        size: { width:12240, height:15840 },
        margin: { top:1080, right:1080, bottom:1080, left:1080 }
    }}, children: [

// ════════════════════════════════════════════════════════════════
// TITLE PAGE
// ════════════════════════════════════════════════════════════════
new Paragraph({ spacing:{ before:1800, after:200 }, alignment: AlignmentType.CENTER,
    children:[new TextRun({ text:"Checkers Game — Defense Study Guide", font:"Arial", size:56, bold:true, color:"1F4E79" })] }),
new Paragraph({ spacing:{ before:200, after:200 }, alignment: AlignmentType.CENTER,
    children:[new TextRun({ text:"Complete explanation of every component, every connection, and every tool", font:"Arial", size:28, color:"404040", italics:true })] }),
new Paragraph({ spacing:{ before:400, after:200 }, alignment: AlignmentType.CENTER,
    children:[new TextRun({ text:"Student: Nir Levy  |  ID: 315699694", font:"Arial", size:24, color:"2E75B6", bold:true })] }),
new Paragraph({ spacing:{ before:100, after:200 }, alignment: AlignmentType.CENTER,
    children:[new TextRun({ text:".NET Network Programming  |  Arnon Barkat  |  Semester A 2026", font:"Arial", size:22, color:"606060" })] }),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 1 — THE BIG PICTURE
// ════════════════════════════════════════════════════════════════
h1("Chapter 1 — The Big Picture"),
p("Before looking at any code, you need to understand what this project IS and why it has multiple parts."),
gap(),
h2("1.1  What is this project?"),
p("A networked checkers-like game. A human player uses a Windows desktop application (WinForms) to play against a server. The server decides the computer's moves and stores all game data in a database. There is also a website where players register and view statistics."),
gap(),
h2("1.2  The 5 projects — what each one does"),
p("The solution is split into 5 C# projects. Each has a single responsibility:"),
gap(),
tbl(
  ["Project","Type","What it does","Runs where?"],
  [
    ["CheckersGame.Shared","Class Library","Common code used by multiple projects (DTOs, models, enums, BoardSerializer)","Not deployed — just compiled into others"],
    ["CheckersGame.Data","Class Library","Database definitions (EF Core entities, DbContext, migrations)","Not deployed — compiled into Api and Web"],
    ["CheckersGame.Api","ASP.NET Core Web API","Game server — receives moves, validates them, returns server moves, stores games in DB","Runs as HTTP server (localhost:5000)"],
    ["CheckersGame.Web","ASP.NET Core Razor Pages","Website — player registration, 9 query pages, update, delete, about page","Runs as HTTP server (localhost:5001)"],
    ["CheckersGame.Client","WinForms (.NET 8)","The Windows desktop app the player actually uses to play","Runs on player's PC"],
  ],
  [2200,2000,4200,1960]
),
gap(),
h2("1.3  Who talks to whom?"),
p("This is the most important thing to understand. Not every project talks to every other project:"),
gap(),
tbl(
  ["Who sends","Who receives","How","What for"],
  [
    ["Client","Api","HTTP (HttpClient)","Register players, start game, send move, receive server move, timeout"],
    ["Api","CheckersGame.Data","EF Core (in-memory)","Read/write games, players, countries from the central database"],
    ["Web","CheckersGame.Data","EF Core (in-memory)","Read/write for registration, queries, update, delete"],
    ["Client","CheckersReplayDb","EF Core (local file)","Save finished games for local replay playback"],
    ["Web","Api","NONE — they share the same database","Web and Api both use CheckersCentralDb independently"],
  ],
  [1800,1800,1700,5060]
),
gap(),
note("The Client NEVER touches the central database directly. It always goes through the Api. The Web NEVER calls the Api — they are separate services that share the same database."),
gap(),
h2("1.4  The two databases"),
tbl(
  ["Database","Location","Used by","Contains"],
  [
    ["CheckersCentralDb","SQL Server LocalDB (on server)","Api + Web","Countries, Players, Games, GamePlayers"],
    ["CheckersReplayDb","SQL Server LocalDB (on client PC)","Client only","ReplayGames, ReplayMoves (for watching old games)"],
  ],
  [2400,2800,2000,3160]
),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 2 — SHARED
// ════════════════════════════════════════════════════════════════
h1("Chapter 2 — CheckersGame.Shared (The Common Library)"),
p("This project contains code that is needed by MORE than one project. Instead of copying the same code into Api and Client (which would mean two places to fix bugs), we put it here once and both projects reference it."),
gap(),
h2("2.1  Enums — named numbers"),
p("An enum is just a way to give names to integers so the code is readable. Instead of writing 'if (status == 2)' you write 'if (status == GameStatus.ServerWon)'."),
gap(),
h3("Side enum  —  file: Shared/Enums/Side.cs"),
tbl(["Value","Meaning"],[ ["Human","The human player's pieces"],["Server","The computer/server's pieces"] ],[4000,6360]),
gap(),
h3("GameStatus enum  —  file: Shared/Enums/GameStatus.cs"),
tbl(["Value","Integer stored in DB","Meaning"],
  [["InProgress","0","Game is still running"],["HumanWon","1","Human player won"],["ServerWon","2","Computer won"],["Abandoned","3","Player ran out of time"]],
  [2200,2600,5560]),
gap(),
h2("2.2  BoardModel  —  file: Shared/Models/BoardModel.cs"),
p("This class represents the state of the game board in memory. It is NOT saved to the database directly — instead it is serialized (converted to a JSON string) first."),
gap(),
tbl(["Property","Type","Meaning"],
  [
    ["Rows","const int = 8","The board has 8 rows (0 = top, 7 = bottom)"],
    ["Cols","const int = 4","The board has 4 columns (0 = left, 3 = right)"],
    ["Cells[r,c]","Side? (nullable)","null = empty square. Side.Human or Side.Server = a piece is there"],
    ["UsedBackward[r,c]","bool","true = this piece has already used its one backward move (cannot go backward again)"],
  ],
  [2200,2400,5760]),
gap(),
note("Human pieces start at rows 6 and 7. Server pieces start at rows 0 and 1. Human moves upward (decreasing row). Server moves downward (increasing row)."),
gap(),
h2("2.3  DTOs — Data Transfer Objects"),
p("A DTO is a simple class whose only job is to carry data between the Client and the Api over HTTP. They have no logic — just properties. Think of them as the 'forms' you fill in when sending an HTTP request or receiving a response."),
gap(),
h3("DTOs used when starting a game"),
tbl(["DTO","Direction","Properties","What it is"],
  [
    ["StartGameRequest","Client -> Api","PlayerIds (List<int>), TimePerMoveSec (int)","Client sends: which players and how many seconds per turn"],
    ["StartGameResponse","Api -> Client","GameId, InitialBoard (JSON string), FirstHumanPlayerId, StartedAt","Api responds with the game ID and the starting board"],
  ],
  [2600,1800,3500,2460]),
gap(),
h3("DTOs used when making a move"),
tbl(["DTO","Direction","Properties","What it is"],
  [
    ["MoveRequest","Client -> Api","GameId, PlayerId, Move (MoveDto)","Client sends: which game, which player, and the move details"],
    ["MoveResponse","Api -> Client","BoardJson, ServerMove (MoveDto), GameOver (bool), Winner (GameStatus?)","Api responds with updated board, server's move, and whether game ended"],
    ["MoveDto","Both directions","FromRow, FromCol, ToRow, ToCol, IsCapture, CapturedRow, CapturedCol, IsBackward","Describes one single move — where a piece moved from and to"],
  ],
  [2200,1800,3800,2560]),
gap(),
h3("Other DTOs"),
tbl(["DTO","Used for"],
  [
    ["PlayerDto","Api sends player details to Client (FirstName, Phone, Country name)"],
    ["TimeoutRequest","Client tells Api that the player ran out of time (sends GameId + PlayerId)"],
  ],
  [2400,7960]),
gap(),
h2("2.4  BoardSerializer  —  file: Shared/BoardSerializer.cs"),
p("The database cannot store a two-dimensional array. BoardSerializer converts the BoardModel to a flat JSON array of integers, and back again."),
gap(),
pb("Serialize(board):", " converts BoardModel into a JSON string like [1,0,2,0,0,0,...]. The array has 64 numbers (32 squares × 2 values each). For each square: first number = 0 (empty), 1 (Human), 2 (Server). Second number = 0 (has not used backward move) or 1 (has used it)."),
pb("Deserialize(json):", " takes that JSON string and reconstructs a BoardModel object."),
gap(),
note("BoardSerializer lives in Shared so BOTH the Api (GameService) and the Client (BoardForm, GameSetupForm) can use the exact same code. Before it was in Shared, there were duplicate DeserializeBoard methods in the Client — now there is only one."),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 3 — DATA
// ════════════════════════════════════════════════════════════════
h1("Chapter 3 — CheckersGame.Data (The Database Layer)"),
p("This project defines what the database looks like. It uses Entity Framework Core (EF Core) — a library that lets you define database tables as C# classes, and then reads/writes data using LINQ instead of SQL."),
gap(),
h2("3.1  What is Entity Framework Core?"),
p("Normally, to talk to a database you write SQL: 'SELECT * FROM Players WHERE Id = 5'. EF Core lets you write C# instead: '_db.Players.FirstOrDefault(p => p.Id == 5)'. EF Core translates your C# into SQL and sends it to the database."),
gap(),
tbl(["Concept","What it means in plain English"],
  [
    ["Entity","A C# class that represents a database table. One class = one table."],
    ["DbContext","The main class you use to talk to the database. It has one DbSet property per table."],
    ["DbSet<T>","Represents one table. _db.Players = the Players table. You can query it with LINQ."],
    ["Migration","A C# file that describes a database change (create table, add column, etc.). EF Core generates these automatically."],
    ["Navigation property","A property on an entity that links to another entity. E.g., Player.Country lets you access the country object directly."],
  ],
  [2800,7560]),
gap(),
h2("3.2  The 4 entities (tables) in CheckersCentralDb"),
gap(),
h3("Country  —  file: Data/Entities/Country.cs"),
tbl(["Column","Type","Notes"],
  [
    ["Id","int","Primary key, auto-incremented"],
    ["Name","string","Unique — no two countries can have the same name. Pre-seeded with 8 countries."],
    ["Players","ICollection<Player>","Navigation property — lets you get all players from this country"],
  ],
  [2000,2000,6360]),
gap(),
note("Countries are seeded automatically when the database is created. You can see the seed data in CheckersCentralDb.cs, in the OnModelCreating method."),
gap(),
h3("Player  —  file: Data/Entities/Player.cs"),
tbl(["Column","Type","Notes"],
  [
    ["Id","int","NOT auto-incremented — the player CHOOSES their own ID (1–1000). Must be unique."],
    ["FirstName","string","At least 2 characters, max 50."],
    ["Phone","string","Exactly 10 digits. Enforced by a CHECK constraint in the database."],
    ["CountryId","int","Foreign key to Countries table."],
    ["RegisteredAt","DateTime","When the player registered."],
    ["Country","Country","Navigation property — lets you access Country.Name directly."],
    ["GamePlayers","ICollection<GamePlayer>","Navigation property — all games this player participated in."],
  ],
  [2000,2000,6360]),
gap(),
h3("Game  —  file: Data/Entities/Game.cs"),
tbl(["Column","Type","Notes"],
  [
    ["Id","int","Primary key, auto-incremented."],
    ["StartTime","DateTime","When the game started (stored as local time)."],
    ["EndTime","DateTime?","Null while game is in progress. Set when game ends."],
    ["TimePerMoveSec","int","Seconds per turn — 2, 5, 10, or 15."],
    ["Status","GameStatus","Stored as int: 0=InProgress, 1=HumanWon, 2=ServerWon, 3=Abandoned."],
    ["NumberOfPlayers","int","How many humans are sharing the screen (1 or 2)."],
    ["BoardJson","string","The current board state, serialized by BoardSerializer as a JSON array."],
    ["MovesCount","int","Total moves made so far."],
    ["CurrentTurnIndex","int","Which player's turn it is (used for round-robin with multiple players)."],
    ["GamePlayers","ICollection<GamePlayer>","Navigation property — which players are in this game."],
  ],
  [2400,2000,5960]),
gap(),
h3("GamePlayer  —  file: Data/Entities/GamePlayer.cs"),
p("This is a JOIN TABLE — it links Players to Games. Because one player can play many games, and one game can have many players, we need a table in the middle."),
gap(),
tbl(["Column","Type","Notes"],
  [
    ["Id","int","Primary key, auto-incremented."],
    ["GameId","int","Foreign key to Games. If the game is deleted, this row is deleted too (CASCADE)."],
    ["PlayerId","int","Foreign key to Players. If the player is deleted, this row is deleted too (CASCADE)."],
    ["TurnOrder","int","1-based position — used to decide whose turn it is in multi-player games."],
  ],
  [2000,2000,6360]),
gap(),
h2("3.3  CheckersCentralDb (the DbContext)  —  file: Data/Context/CheckersCentralDb.cs"),
p("This is the class you inject everywhere you need to talk to the database. It inherits from DbContext (EF Core base class)."),
gap(),
pb("DbSet properties:", " Countries, Players, Games, GamePlayers. These are the four 'doors' into the database tables."),
pb("OnModelCreating:", " This method runs once when EF Core sets up the database. Inside it we define: unique index on Country.Name, CHECK constraints on Player.Id (1-1000) and Player.Phone (10 digits), cascade/restrict delete behaviors, and the seed data for Countries."),
gap(),
note("Whenever a Razor Page or API Controller needs the database, ASP.NET automatically creates a CheckersCentralDb instance and passes it to the constructor — this is called Dependency Injection."),
gap(),
h2("3.4  CheckersReplayDb  —  file: Client/LocalDb/CheckersReplayDb.cs"),
p("This is a SECOND, separate database that lives on the CLIENT's computer (not the server). It only stores replay data for games that player has played."),
gap(),
tbl(["Table","Columns","Purpose"],
  [
    ["ReplayGames","Id, ServerGameId, PlayersJson, StartTime, DurationSec, TimePerMoveSec, WinnerSide","One row per saved game."],
    ["ReplayMoves","Id, ReplayGameId, MoveNumber, Side, FromRow, FromCol, ToRow, ToCol, CapturedRow, CapturedCol, IsBackward","One row per move in that game."],
  ],
  [2200,4000,4160]),
gap(),
h2("3.5  Migrations — how the database gets created"),
p("Migrations are auto-generated C# files that describe what the database should look like. When you run the API or Web app for the first time, EF Core looks at the migration files and runs the SQL to create all the tables."),
gap(),
tbl(["Migration file","What it does"],
  [
    ["20260423104421_InitialCreate","Creates Countries, Players, Games, GamePlayers tables and seeds Country data"],
    ["20260423142146_AddMovesCountAndFixCascade","Adds MovesCount and CurrentTurnIndex columns, fixes cascade rules"],
    ["20260423142805_RemoveMovesTable","Removes an early Moves table that was replaced by storing BoardJson directly"],
  ],
  [4000,6360]),
gap(),
note("You NEVER edit migration files by hand. If you change an entity class, you run 'dotnet ef migrations add <name>' and EF Core generates a new migration automatically."),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 4 — API
// ════════════════════════════════════════════════════════════════
h1("Chapter 4 — CheckersGame.Api (The Game Server)"),
p("This is an ASP.NET Core Web API project. It listens for HTTP requests from the Client and responds with JSON. It contains all the game logic — move validation, server move generation, and game state management."),
gap(),
h2("4.1  What is a Web API?"),
p("A Web API is a program that listens on a port (like a phone waiting for calls). When the Client sends an HTTP request (like GET /api/players/5 or POST /api/games/move), the API processes it and sends back a JSON response. The Client uses HttpClient to make these calls."),
gap(),
tbl(["HTTP method","When you use it","Example"],
  [
    ["GET","Read data — no changes to the database","GET /api/players/5  → returns Player with Id=5"],
    ["POST","Create something or perform an action","POST /api/games/start  → starts a new game"],
  ],
  [1800,3200,5360]),
gap(),
h2("4.2  Program.cs — the startup file"),
p("Program.cs is where the API is configured and started. Every service that a controller needs must be registered here first (this is called Dependency Injection registration)."),
gap(),
pb("builder.Services.AddDbContext<CheckersCentralDb>(...)", "  — registers the database so controllers can receive it in their constructor."),
pb("builder.Services.AddScoped<GameService>()", "  — registers GameService so controllers can receive it."),
pb("builder.Services.AddControllers()", "  — tells ASP.NET to look for Controller classes and wire them up to HTTP routes."),
gap(),
h2("4.3  PlayersController  —  file: Api/Controllers/PlayersController.cs"),
p("Handles all HTTP requests about players."),
gap(),
tbl(["Endpoint","HTTP method","What it does","Called by"],
  [
    ["api/players/{id}","GET","Returns a PlayerDto for the given ID. Returns 404 if not found.","Client — to show player info at game start"],
    ["api/players","POST","Creates a new player in the database.","Web — registration page calls this after saving to its own DB... actually the Web uses EF directly, not the Api"],
  ],
  [2600,1600,3800,2360]),
gap(),
note("The Web project does NOT call the Api to create players. Both Api and Web have direct access to CheckersCentralDb. The Client calls GET /api/players/{id} to fetch player details when starting a game."),
gap(),
h2("4.4  GamesController  —  file: Api/Controllers/GamesController.cs"),
p("Handles all HTTP requests about games. This is the heart of the game communication."),
gap(),
tbl(["Endpoint","HTTP method","What it does"],
  [
    ["api/games/start","POST","Creates a new game in the DB, returns the initial board. Calls GameService.StartGameAsync()."],
    ["api/games/move","POST","Receives a human move, validates it, picks server move, updates DB, returns new board. Calls GameService.HandleMoveAsync()."],
    ["api/games/timeout","POST","Called when human runs out of time. Sets game status to Abandoned. Calls GameService.HandleTimeoutAsync()."],
  ],
  [2400,1600,6360]),
gap(),
h2("4.5  GameService  —  file: Api/Services/GameService.cs"),
p("GameService contains all the game logic. Controllers are thin — they just call GameService methods. This separation keeps the code clean."),
gap(),
h3("StartGameAsync(StartGameRequest req)"),
p("Creates a new BoardModel (fresh board with pieces in starting positions), serializes it, saves a new Game to the database with all the player links, and returns the game ID and initial board JSON."),
gap(),
h3("HandleMoveAsync(MoveRequest req)"),
p("This is called every time the human makes a move. Here is what happens step by step:"),
gap(),
numbered("Load the game from the database using GameId."),
numbered("Deserialize the BoardJson back into a BoardModel using BoardSerializer.Deserialize()."),
numbered("Call MoveValidator.Validate() to check the human's move is legal. If not, return an error."),
numbered("Apply the human's move to the board (move piece, remove captured piece if any)."),
numbered("Check if the human has won (reached the opposite back row, or blocked all server pieces)."),
numbered("If game is not over: call MoveValidator.GetRandomServerMove() to pick a random legal move for the server."),
numbered("Apply the server's move to the board."),
numbered("Check if the server has won."),
numbered("Serialize the updated board back to JSON and save to the database."),
numbered("Return MoveResponse with the new BoardJson, the server's move, and whether the game is over."),
gap(),
h3("HandleTimeoutAsync(TimeoutRequest req)"),
p("Simply sets game.Status = GameStatus.Abandoned and game.EndTime = DateTime.Now, then saves to the database."),
gap(),
h2("4.6  MoveValidator  —  file: Api/GameEngine/MoveValidator.cs"),
p("This class knows all the game rules. It has two main methods:"),
gap(),
h3("Validate(board, move, side)  —  checks if a specific move is legal"),
p("Returns (bool isValid, string errorMessage). Checks:"),
bullet("The piece at the from-position belongs to the moving side."),
bullet("For a normal forward move: the destination is diagonally forward by 1 row, empty."),
bullet("For a backward move: diagonally backward by 1 row, empty, AND this piece has not used its backward move yet."),
bullet("For a capture: jump exactly 2 rows forward + 2 columns diagonally. Enemy piece must be at midpoint. Landing square must be empty."),
gap(),
h3("GetMovesForPiece(board, row, col, side)  —  returns all legal moves for one piece"),
p("Loops through all possible directions and returns a list of MoveDto objects. Used by the server to find all legal moves and pick one at random."),
gap(),
pb("Capture geometry (important!):", " A capture jumps 2 rows and 2 columns. The enemy piece is at (row+1, col+1) or similar, and you land at (row+2, col+2). The midpoint formula is midCol = (fromCol + toCol) / 2 — this is exact because the difference is always 2."),
gap(),
note("The Client also has ClientMoveValidator.cs which is a copy of the same logic. It is used client-side to highlight legal moves when a player clicks a piece. The actual validation that COUNTS is always done server-side in MoveValidator."),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 5 — WEB
// ════════════════════════════════════════════════════════════════
h1("Chapter 5 — CheckersGame.Web (The Website)"),
p("This is an ASP.NET Core Razor Pages project. Razor Pages is a web framework where each page consists of two files: a .cshtml file (HTML + Razor syntax) and a .cshtml.cs file (the C# code behind that page)."),
gap(),
h2("5.1  What is Razor Pages?"),
tbl(["Concept","Plain English explanation"],
  [
    ["Page (.cshtml)","The HTML template. Uses @Model.Something to display data from the PageModel. Uses <form> tags for user input."],
    ["PageModel (.cshtml.cs)","The C# class behind the page. Has OnGet() (runs when you open the page) and OnPost() (runs when you submit a form)."],
    ["[BindProperty]","Tells Razor to automatically fill a property from the submitted form data. No manual Request.Form[\"name\"] needed."],
    ["asp-for","HTML helper that binds an input field to a [BindProperty] property AND adds validation attributes."],
    ["asp-validation-for","Shows the error message for a specific field if validation fails."],
    ["asp-validation-summary","Shows all error messages at once at the top of the form."],
    ["asp-page","Creates a link to another Razor page. <a asp-page=\"/Register\"> becomes <a href=\"/Register\">."],
  ],
  [2800,7560]),
gap(),
h2("5.2  _Layout.cshtml — the shared template"),
p("Every page on the website uses _Layout.cshtml as its outer shell. It contains the navigation bar at the top with links to all pages. All navigation links use asp-page= (never href=) as required by the spec."),
gap(),
h2("5.3  Register.cshtml — player registration"),
p("This is the most complex page. It lets up to 10 players register before a game starts."),
gap(),
pb("How it works — OnGet():", " Loads the Countries list from the database for the dropdown. Also reads PlayerCount from the query string if coming back with errors."),
pb("How it works — OnPost():", " Receives all the player data via [BindProperty]. Validates each player. Checks that IDs are not already in the database and not duplicated within the form. Creates the Game and all Players in the database. Redirects the Client to start the game."),
gap(),
tbl(["Validation rule","Where it is enforced"],
  [
    ["FirstName: at least 2 characters","[MinLength(2)] attribute on the model + custom error message"],
    ["ID: 1-1000 whole number","[Range(1,1000)] + database CHECK constraint"],
    ["ID: must not already exist","Manual check in OnPost() against the database"],
    ["Phone: exactly 10 digits","[RegularExpression] + database CHECK constraint"],
    ["Country: must be selected","[Required] attribute"],
  ],
  [3600,6760]),
gap(),
note("Custom error messages are defined in the InputModel class inside Register.cshtml.cs. The ErrorMessage parameter on each attribute overrides the default Razor message."),
gap(),
h2("5.4  The 9 Query pages  —  folder: Web/Pages/Queries/"),
p("Each query page has a OnGetAsync() method that builds the result using LINQ — NO for/foreach/while loops allowed inside the method. Here is what each query shows:"),
gap(),
tbl(["Page file","Spec §","What it shows"],
  [
    ["AllPlayers.cshtml","§22","All players who played at least 1 finished game, with all details. Sortable A-Z or Z-A (case-insensitive)."],
    ["PlayersByName.cshtml","§23","Same players, sorted Z-A by name (case-insensitive). Shows only Name + date of last game (2 columns)."],
    ["AllGames.cshtml","§24","All games with all details (ID, start, end, duration, time per move, status, players)."],
    ["FirstByCountry.cshtml","§25","From each country: only the player who played FIRST (earliest game start date)."],
    ["GamesByPlayer.cshtml","§26","A dropdown of all player names (no case-insensitive duplicates). Select one to see all their games."],
    ["GamesPerPlayer.cshtml","§27","Every player and how many games they played. 2 columns only: Name + Count."],
    ["GroupedByCount.cshtml","§28","Players grouped by game count, sorted most-to-least. Includes players with 0 games ('Did not play' group)."],
    ["ByCountry.cshtml","§29","Players grouped by country."],
    ["TopCountries.cshtml","§30","Top 2 countries with most game participations. 2 columns only: Country + Count."],
  ],
  [2800,1000,6560]),
gap(),
h3("Two-step LINQ pattern (important for defense!)"),
p("Some queries cannot be done in a single LINQ expression that EF Core can translate to SQL. For example, GroupBy followed by First() or ValueTuple.Create() are not supported. The solution is a two-step pattern:"),
gap(),
code("Step 1: Query the database with an anonymous type → .ToListAsync()  (this runs SQL)"),
code("Step 2: In-memory .Select() or .GroupBy() to convert to the final format  (this runs in C#)"),
gap(),
p("Example from GamesPerPlayer (§27):"),
code("var rows = await _db.Players"),
code("    .Select(p => new { p.FirstName, Count = p.GamePlayers.Count() })"),
code("    .OrderBy(p => p.FirstName.ToLower())"),
code("    .ToListAsync();                         // <-- SQL runs here"),
code("Results = rows.Select(x => (x.FirstName, x.Count)).ToList();  // <-- C# conversion"),
gap(),
h2("5.5  EditPlayer.cshtml — update player (§31)"),
p("Allows changing FirstName, Phone, and Country. The player ID is shown as read-only text — it cannot be changed. OnPost() loads the existing player, updates only the three allowed fields, calls SaveChangesAsync()."),
gap(),
h2("5.6  Delete.cshtml — delete game or player (§32)"),
p("Has two separate forms on the same page: one to delete a game by ID, one to delete a player by ID. Deletions happen at the database level — no 'deleted' flag. Cascade delete is configured in the DbContext: deleting a player automatically deletes their GamePlayer rows."),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 6 — CLIENT
// ════════════════════════════════════════════════════════════════
h1("Chapter 6 — CheckersGame.Client (The Windows App)"),
p("This is a WinForms application — a traditional Windows desktop app. It is what the player actually sees and uses. It communicates with the Api over HTTP using HttpClient."),
gap(),
h2("6.1  The 4 forms (windows)"),
tbl(["Form file","What the user sees","Opens when"],
  [
    ["GameSetupForm.cs","Player ID input fields, time-per-move dropdown, Start Game button","App starts"],
    ["BoardForm.cs","The game board with pieces, timer countdown, free-drawing, New Game button","Game starts successfully"],
    ["ReplayListForm.cs","A list of past games saved locally","User clicks 'Replay' button"],
    ["ReplayBoardForm.cs","The board replaying moves automatically one by one","User selects a game from ReplayListForm"],
  ],
  [2400,3800,4160]),
gap(),
h2("6.2  CheckersApiClient  —  file: Client/ApiClient/CheckersApiClient.cs"),
p("This class wraps all HTTP calls to the Api. Instead of writing HttpClient code all over the forms, every form uses this one class."),
gap(),
tbl(["Method","HTTP call","Returns"],
  [
    ["GetPlayerAsync(id)","GET /api/players/{id}","PlayerDto? — null if player not found (404), throws on other errors"],
    ["StartGameAsync(request)","POST /api/games/start","StartGameResponse — the game ID and initial board"],
    ["SendMoveAsync(request)","POST /api/games/move","MoveResponse — new board, server's move, game over flag"],
    ["TimeoutAsync(gameId, playerId)","POST /api/games/timeout","void — tells server the player ran out of time"],
  ],
  [2800,2800,4760]),
gap(),
note("GetPlayerAsync uses GetAsync() + manual 404 check instead of GetFromJsonAsync(). This is because GetFromJsonAsync() automatically throws an exception on 404, which would show a 'cannot connect' error instead of 'player not found'."),
gap(),
h2("6.3  GameSetupForm — how a game starts"),
p("The form has fields for 1 or 2 player IDs and a combo box with time options (2 / 5 / 10 / 15 seconds). When Start Game is clicked:"),
numbered("Calls GetPlayerAsync() for each player ID. Shows 'Player not found' if 404."),
numbered("Calls StartGameAsync() with the player IDs and selected time. The Api creates the game."),
numbered("Deserializes the InitialBoard JSON using BoardSerializer.Deserialize()."),
numbered("Opens BoardForm, passing it the board, game ID, players, and time setting."),
gap(),
h2("6.4  BoardForm — the game board"),
p("This is the most complex form. It handles drawing, animation, moves, timer countdown, and saving replays."),
gap(),
h3("The Rectangle[,] matrix (§14)"),
p("The board is stored as Rectangle[8,4] — a two-dimensional array of Rectangle objects. Each Rectangle stores the pixel coordinates (X, Y, Width, Height) of one cell on screen. When the board is drawn, we loop through this matrix and draw at those coordinates. This is a requirement from the spec."),
gap(),
h3("Drawing with Graphics (§15)"),
p("The board is drawn inside the BoardPB_Paint event handler (PictureBox Paint event). This fires every time _boardPB.Invalidate() is called. The 'g' parameter is a Graphics object that has methods like:"),
bullet("g.FillRectangle(brush, rect) — fills a cell with a color"),
bullet("g.FillEllipse(brush, rect) — draws a circular piece"),
bullet("g.DrawImage(bitmap, 0, 0) — draws the free-drawing overlay on top"),
gap(),
h3("The two Timers (§15)"),
tbl(["Timer","Interval","Purpose"],
  [
    ["_countdownTimer","1000ms (1 second)","Counts down seconds remaining in the current turn. When it hits 0, calls TimeoutAsync()."],
    ["_animTimer","50ms (20 fps)","Drives smooth animations: the pulsing piece size (Math.Sin), the fade-out highlight on last-moved squares."],
    ["_winTimer","300ms","The win blink animation — toggles _winBlinkOn true/false. Stops after 17 ticks (= ~5 seconds)."],
  ],
  [2200,2000,6160]),
gap(),
h3("Free drawing with Bitmap (§15)"),
p("A transparent Bitmap the same size as the board is kept in memory as _drawBitmap. A Graphics object (_drawGraphics) is created from this bitmap. When the user right-click-drags the mouse, DrawLine is called on _drawGraphics. At paint time, the bitmap is drawn on top of the board. The Clear Drawing button calls _drawGraphics.Clear(Color.Transparent)."),
gap(),
pb("Why Bitmap and not a List of points?", " The spec explicitly requires Bitmap. Storing a List of points would require redrawing every line on every paint event, which is slower and harder to clear."),
gap(),
h3("Win blink animation (§16)"),
p("When HandleGameOver() is called: _winnerSide is set, _winBlink = true, and _winTimer starts. Every 300ms, WinTimer_Tick toggles _winBlinkOn. In the paint method, if _winBlink && _winBlinkOn, winner pieces are drawn in LimeGreen instead of their normal color. After 17 ticks (= 5.1 seconds), the timer stops and pieces return to normal."),
gap(),
h3("Saving the replay"),
p("When a game ends, SaveReplayToDb() runs. It creates a new CheckersReplayDb() (EF Core DbContext for the local database), inserts a ReplayGame row and one ReplayMove row for every move in _moveHistory, then calls SaveChangesAsync()."),
gap(),
h2("6.5  ReplayListForm and ReplayBoardForm — watching old games"),
p("ReplayListForm opens a CheckersReplayDb(), loads all ReplayGames, and shows them in a list. When the user selects one and clicks Watch, ReplayBoardForm opens."),
gap(),
p("ReplayBoardForm loads all the ReplayMoves for that game. It uses a Timer set to an equal interval (e.g., 800ms). Each timer tick applies the next move to the board and calls Invalidate() — the board animates through the game automatically. It is read-only: no clicking, no player input."),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 7 — COMPLETE FLOW EXAMPLES
// ════════════════════════════════════════════════════════════════
h1("Chapter 7 — Complete Flow Examples"),
p("This chapter traces exactly what happens, step by step, when a user performs common actions. Knowing these flows by heart is essential for the defense."),
gap(),
h2("Flow 1 — Registering players and starting a game"),
gap(),
numbered("User opens the website (CheckersGame.Web) in their browser."),
numbered("User goes to the Register page. OnGet() runs — loads Countries from DB for the dropdown combo."),
numbered("User selects 2 players, fills in names, IDs, phones, countries. Clicks Register."),
numbered("OnPost() runs in Register.cshtml.cs."),
numbered("Validates all fields (length, range, phone format)."),
numbered("Queries DB: checks no player with those IDs already exists."),
numbered("Creates a Game entity and two Player entities. Saves to CheckersCentralDb via EF Core."),
numbered("Redirects browser to a success/confirmation page with the game ID."),
numbered("User opens the WinForms Client app (CheckersGame.Client)."),
numbered("In GameSetupForm: user enters the player IDs, selects 10 seconds, clicks Start."),
numbered("Client calls GET /api/players/1 — Api returns PlayerDto for player 1."),
numbered("Client calls GET /api/players/2 — Api returns PlayerDto for player 2."),
numbered("Client calls POST /api/games/start with {PlayerIds:[1,2], TimePerMoveSec:10}."),
numbered("Api.GamesController calls GameService.StartGameAsync() — creates board, saves Game to DB, returns game ID + board JSON."),
numbered("Client receives StartGameResponse — deserializes board, opens BoardForm."),
gap(),
h2("Flow 2 — Human makes a move"),
gap(),
numbered("User clicks a piece on the board (BoardForm.BoardPB_MouseDown)."),
numbered("ClientMoveValidator.GetMovesForPiece() finds all legal moves for that piece. Legal target squares are highlighted green."),
numbered("User clicks a destination square."),
numbered("Client calls POST /api/games/move with {GameId, PlayerId, Move: {FromRow, FromCol, ToRow, ToCol, ...}}."),
numbered("GamesController receives request, calls GameService.HandleMoveAsync()."),
numbered("GameService loads game from DB, deserializes board, calls MoveValidator.Validate() — returns error if illegal."),
numbered("Move is applied to the board. Win condition is checked."),
numbered("If not won: GetRandomServerMove() picks a random legal server move. Server move is applied. Win checked again."),
numbered("Board is serialized, saved to DB (MovesCount++, BoardJson updated)."),
numbered("MoveResponse returned: new board JSON, server's MoveDto, GameOver flag."),
numbered("Client receives response. Deserializes new board. Animates server piece moving. Redraws board."),
numbered("If GameOver: HandleGameOver() runs — win blink starts, SaveReplayToDb() saves to local DB."),
gap(),
h2("Flow 3 — Player runs out of time"),
gap(),
numbered("_countdownTimer hits 0 in BoardForm."),
numbered("CountdownTimer_Tick() stops the countdown, sets _gameOver = true."),
numbered("Calls _api.TimeoutAsync(gameId, playerId)."),
numbered("Api sets game.Status = Abandoned, game.EndTime = DateTime.Now, saves to DB."),
gap(),
h2("Flow 4 — Watching a replay"),
gap(),
numbered("User clicks Replay button in the app. ReplayListForm opens."),
numbered("Opens CheckersReplayDb() (local database). Loads all ReplayGames — shows them in a ListBox."),
numbered("User selects a game and clicks Watch. ReplayBoardForm opens."),
numbered("ReplayBoardForm loads all ReplayMoves for that game from CheckersReplayDb."),
numbered("A Timer fires every 800ms. Each tick: applies the next move to the board, calls Invalidate()."),
numbered("Board draws each move in sequence with animation. After last move, timer stops."),
PB(),

// ════════════════════════════════════════════════════════════════
// CHAPTER 8 — WHERE TO CHANGE THINGS
// ════════════════════════════════════════════════════════════════
h1("Chapter 8 — Where to Change Things"),
p("If the examiner asks you to change something during the defense, use this table to know exactly where to go."),
gap(),
tbl(["If you need to change...","Go to this file","Look for..."],
  [
    ["Game rules (what moves are legal)","Api/GameEngine/MoveValidator.cs","Validate() method"],
    ["How the server picks its move","Api/GameEngine/MoveValidator.cs","GetRandomServerMove() / GetMovesForPiece()"],
    ["Board size (rows/cols)","Shared/Models/BoardModel.cs","Rows and Cols constants"],
    ["How the board is saved to/from JSON","Shared/BoardSerializer.cs","Serialize() and Deserialize()"],
    ["Time options in the combo (2/5/10/15)","Client/Forms/GameSetupForm.cs","_cboTime.Items.AddRange(...)"],
    ["The win blink duration","Client/Forms/BoardForm.cs","_winBlinkCount >= 17  (17 ticks × 300ms = 5s)"],
    ["Win blink blink speed","Client/Forms/BoardForm.cs","_winTimer.Interval = 300"],
    ["Free drawing color or thickness","Client/Forms/BoardForm.cs","_drawColor and _drawWidth fields"],
    ["Animation speed (piece pulse)","Client/Forms/BoardForm.cs","_animTimer.Interval (currently 50ms = 20fps)"],
    ["Registration validation rules","Web/Pages/Register.cshtml.cs","RegisterInput class attributes (ErrorMessage)"],
    ["Registration page HTML/layout","Web/Pages/Register.cshtml","The @for loop that builds player rows"],
    ["A query result (what columns shown)","Web/Pages/Queries/<QueryName>.cshtml","The @foreach loop in the Razor template"],
    ["A query logic (what data is fetched)","Web/Pages/Queries/<QueryName>.cshtml.cs","OnGetAsync() method"],
    ["Player validation constraints","Data/Context/CheckersCentralDb.cs","OnModelCreating() — HasCheckConstraint calls"],
    ["Country seed data","Data/Context/CheckersCentralDb.cs","mb.Entity<Country>().HasData(...)"],
    ["How games store time","Api/Services/GameService.cs","DateTime.Now for StartTime and EndTime"],
    ["API base URL","Client/ApiClient/CheckersApiClient.cs","_http.BaseAddress = new Uri(...)"],
    ["Replay playback speed","Client/Forms/ReplayBoardForm.cs","Timer interval"],
    ["About page content","Web/Pages/About.cshtml","The HTML directly"],
    ["Database connection string","Api/appsettings.json  or  Web/appsettings.json","ConnectionStrings section"],
  ],
  [3800,3400,3160]),
gap(),
h2("Key terms to know for the defense"),
gap(),
tbl(["Term","One-line explanation"],
  [
    ["Dependency Injection","ASP.NET automatically creates and passes objects (like DbContext) to constructors. You never write 'new CheckersCentralDb()' in controllers."],
    ["EF Core","Library that maps C# classes to database tables. You write LINQ instead of SQL."],
    ["Migration","A file that tells EF Core how to create or modify the database schema."],
    ["DTO","A simple data-carrying class with no logic. Used to transfer data over HTTP as JSON."],
    ["LINQ","C# query syntax: .Where(), .Select(), .OrderBy(), .GroupBy(), .First(), etc."],
    ["HttpClient","The C# class the Client uses to send HTTP requests to the Api."],
    ["async/await","C# pattern for non-blocking operations. 'await' waits for a Task to finish without freezing the app."],
    ["Invalidate()","Tells WinForms to redraw the PictureBox — triggers the Paint event."],
    ["BindProperty","Razor Pages attribute that auto-fills a property from submitted form data."],
    ["Cascade delete","When a parent row is deleted, all related child rows are deleted automatically by the database."],
    ["Scope_Identity / IDENTITY(1,1)","SQL Server auto-increments the Id column for tables that use it (Games, Countries, GamePlayers). Players do NOT use this — they choose their own Id."],
  ],
  [2800,7560]),
gap(),
new Paragraph({ spacing:{ before:400, after:0 }, alignment: AlignmentType.CENTER,
    children:[new TextRun({ text:"Good luck at the defense!", font:"Arial", size:32, bold:true, color:"1F4E79" })] }),
new Paragraph({ spacing:{ before:100, after:0 }, alignment: AlignmentType.CENTER,
    children:[new TextRun({ text:"You built this — you know it.", font:"Arial", size:26, color:"2E75B6", italics:true })] }),

]}]});

Packer.toBuffer(doc).then(buf => {
    fs.writeFileSync("C:\\Visual Studio\\Final project\\DefenseGuide.docx", buf);
    console.log("DefenseGuide.docx created successfully!");
}).catch(err => { console.error("ERROR:", err.message); });
